name: flutter_use

packages:
  - packages/**
  - packages/**/example/*

ide:
  intellij: true
  vscode: true

scripts:
  pub:upgrade:
    run: melos exec -- flutter pub upgrade

  pub:get:
    run: melos exec -- flutter pub get

  analyze: melos exec -- dart analyze .

  format: bash ./scripts/dartfmt.sh
    
  unit:test:
    run: |
      melos exec -- flutter test
    select-package:
      dir-exists:
        - test