name: flutter_use_sensors

description: Collection of Flutter Hooks.
version: 0.0.4
homepage: https://github.com/wasabeef/flutter_use
repository: https://github.com/wasabeef/flutter_use
documentation: https://github.com/wasabeef/flutter_use
issue_tracker: https://github.com/wasabeef/flutter_use/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.0
  sensors_plus: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.3.0
