name: flutter_use_battery

description: Battery monitoring hooks for Flutter applications. Provides useBattery hook for real-time battery level and charging state tracking across platforms.
version: 1.0.0
homepage: https://github.com/wasabeef/flutter_use
repository: https://github.com/wasabeef/flutter_use
documentation: https://github.com/wasabeef/flutter_use
issue_tracker: https://github.com/wasabeef/flutter_use/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.0
  battery_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.3.0
