name: flutter_use_battery

description: Collection of Flutter Hooks.
version: 0.0.4
homepage: https://github.com/wasabeef/flutter_use
repository: https://github.com/wasabeef/flutter_use
documentation: https://github.com/wasabeef/flutter_use
issue_tracker: https://github.com/wasabeef/flutter_use/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.0
  battery_plus: ^2.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.3.0
