name: flutter_use_video

description: Collection of Flutter Hooks.
version: 0.0.2
homepage: https://github.com/wasabeef/flutter_use
repository: https://github.com/wasabeef/flutter_use
documentation: https://github.com/wasabeef/flutter_use
issue_tracker: https://github.com/wasabeef/flutter_use/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  video_player: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.16
